export default function AboutPage() {
	return (
		<>
			<h1>About MoodMix</h1>

			<p>
				MoodMix is a <strong>background-music discovery app</strong>. Instead of
				searching by song or artist, you set the <strong>mood</strong>, dark or
				bright, chill or dynamic, organic or electronic, and the app finds{" "}
				<strong>YouTube music mixes</strong> that fit.
			</p>

			<h2>How it works</h2>

			<p>
				Every mix in the catalog has been listened to and tagged with how it{" "}
				<em>feels</em> across <strong>three dimensions</strong>: mood, energy,
				and whether it leans organic or electronic. When you move the sliders,
				MoodMix finds mixes whose feel is{" "}
				<strong>closest to the combination</strong> you've picked. Genres and
				the instrumental toggle narrow things further.
			</p>

			<p>
				If you'd rather describe a vibe in words, the{" "}
				<strong>AI search bar</strong> takes a sentence, e.g.{" "}
				<em>"afternoon study session"</em>, and sets the sliders and genres for
				you.
			</p>

			<p>
				And if you don't feel like typing or fiddling with anything, the row of{" "}
				<strong>quick tags</strong> just under the top bar gives you one-click
				starting points, ready-made moods you can tap and go.
			</p>

			<h2>Why mixes, not songs?</h2>

			<p>
				Long mixes (<strong>average 45–90 minutes</strong>) are made for
				listening in the background while you work, cook, read, or wind down.
				They need <strong>fewer interruptions</strong> than a song-by-song
				queue, and the best ones are put together by{" "}
				<strong>real people</strong> who care about flow from one track to the
				next, aiming to achieve a <strong>seamless listening experience</strong>
				.
			</p>

			<h2>Real music, made by real people</h2>

			<p>
				A lot of what passes for ambient or chill music online these days is{" "}
				generated by AI, endless looping tracks with no author, no story, and no
				care for how they're put together. MoodMix exists because{" "}
				<strong>that's not what we want to listen to</strong>.
			</p>

			<p>
				Every channel in our catalog is <strong>hand-picked</strong>, and we
				actively screen out sources that rely on AI-generated content. The goal
				is to promote{" "}
				<strong>
					human-made mixes from creators who actually craft their sound
				</strong>{" "}
				, so the music you hear stays organic, intentional, and made by{" "}
				<strong>authentic artists</strong>.
			</p>
		</>
	);
}
